name: imported_styles
version: 1.33.1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  less_dart: ^2.3.5
  angular_components: ^0.13.0+1

dev_dependencies:
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  webdev: ^2.5.8
  pedantic: ^1.8.0
  test: ^1.6.0
