name: angular_app
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  less_dart: ^2.3.5
  imported_styles: any

dev_dependencies:
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  webdev: ^2.5.8
  pedantic: ^1.8.0
  test: ^1.6.0

dependency_overrides:
  imported_styles:
    path: ../imported-styles